# Generated by Django 5.2.7 on 2025-10-11 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(help_text='Empresa a la que pertenece esta sede.', on_delete=django.db.models.deletion.CASCADE, to='candidatos.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('DNI', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('nombres_completos', models.CharField(max_length=255)),
                ('telefono_whatsapp', models.CharField(max_length=9)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True, help_text='Fecha de creación del registro del candidato.')),
                ('estado_actual', models.CharField(choices=[('REGISTRADO', 'Registrado (Primer Contacto)'), ('CONVOCADO', 'Convocado (Segundo Contacto)'), ('CAPACITACION_TEORICA', 'En Capacitación Teórica'), ('CAPACITACION_PRACTICA', 'En Capacitación Práctica'), ('CONTRATADO', 'Contratado')], default='REGISTRADO', max_length=250)),
                ('sede_registro', models.ForeignKey(help_text='Sede donde se registró o fue contactado inicialmente el candidato.', on_delete=django.db.models.deletion.PROTECT, to='candidatos.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de esta convocatoria/proceso.')),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado/Confirmado'), ('TEORIA', 'Capacitación Teórica'), ('PRACTICA', 'Capacitación Práctica'), ('CONTRATADO', 'Contratado'), ('NO_APTO', 'No Apto (No cumple pruebas/objetivos)'), ('ABANDONO', 'Abandono/Deserción')], default='INICIADO', max_length=15)),
                ('objetivo_ventas_alcanzado', models.BooleanField(default=False, help_text='Resultado de la prueba de objetivo de ventas/KPI en práctica.')),
                ('factor_actitud_aplica', models.BooleanField(default=False, help_text="Indica si se queda por 'Actitud' a pesar de fallar otras pruebas (Opción escasa).")),
                ('fecha_contratacion', models.DateField(blank=True, help_text='Fecha de firma del contrato (si aplica).', null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato')),
                ('empresa_proceso', models.ForeignKey(help_text='Cliente para este ciclo de prueba.', on_delete=django.db.models.deletion.CASCADE, to='candidatos.empresa')),
                ('sede_proceso', models.ForeignKey(help_text='Sede donde tomó la prueba.', on_delete=django.db.models.deletion.CASCADE, to='candidatos.sede')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidatos.supervisor')),
            ],
            options={
                'unique_together': {('candidato', 'fecha_inicio', 'empresa_proceso')},
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('TEORIA', 'Teoría'), ('PRACTICA', 'Práctica/Llamada')], max_length=8)),
                ('estado', models.CharField(choices=[('A', 'Asistió'), ('F', 'Faltó'), ('T', 'Tardanza'), ('B', 'Baja/Desistió')], default='F', max_length=1)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.proceso')),
            ],
            options={
                'verbose_name_plural': 'Registros de Asistencia',
                'unique_together': {('proceso', 'fecha', 'tipo')},
            },
        ),
    ]
