# Generated by Django 5.2.7 on 2025-10-17 18:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_alter_proceso_candidato'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCualificacion',
            fields=[
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='candidatos.candidato')),
                ('distrito', models.CharField(help_text='Distrito de residencia.', max_length=100)),
                ('secundaria_completa', models.BooleanField(help_text='¿Tienes secundaria completa?')),
                ('experiencia_campanas_espanolas', models.BooleanField(help_text='¿Has tenido experiencia con campañas españolas como vendedor?')),
                ('experiencia_ventas_tipo', models.CharField(choices=[('CALLCENTER', 'Sí, ventas por teléfono (CALLCENTER)'), ('ESCRITOS', 'Sí, ventas por medios escritos'), ('PRESENCIALES', 'Sí, ventas presenciales'), ('NO', 'No')], default='NO', help_text='Tipo de experiencia en ventas.', max_length=20)),
                ('empresa_vendedor', models.CharField(blank=True, help_text='¿En qué empresa has trabajado como vendedor?', max_length=150, null=True)),
                ('tiempo_experiencia_vendedor', models.CharField(blank=True, choices=[('MENOS_3', 'Menos de 3 meses'), ('MENOS_6', 'Menos de 6 meses'), ('MENOS_1_ANIO', 'Menos de 1 año'), ('MAS_1_ANIO', 'De 1 año a más')], help_text='¿Cuánto tiempo de experiencia has tenido como vendedor?', max_length=20, null=True)),
                ('conforme_beneficios', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No'), ('OTRO', 'Otro')], help_text='¿Estás conforme con los beneficios que te damos?', max_length=10)),
                ('detalle_beneficios_otro', models.TextField(blank=True, help_text="Detalle si la respuesta a beneficios fue 'Otro'.", null=True)),
                ('disponibilidad_horario', models.BooleanField(help_text='¿Tienes disponibilidad para trabajar en el horario de 06:15am a 03:00pm?')),
                ('discapacidad_enfermedad_cronica', models.TextField(blank=True, help_text='¿Tienes alguna discapacidad o enfermedad crónica?', null=True)),
                ('dificultad_habla', models.BooleanField(help_text='¿Tienes alguna dificultad en el habla?')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='distrito',
            field=models.CharField(default=datetime.datetime(2025, 10, 17, 18, 56, 38, 847821, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
