# Generated by Django 5.2.7 on 2025-10-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0003_datoscualificacion_candidato_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='fecha_practico',
            field=models.DateField(blank=True, help_text='Fecha en que el candidato ingresó a Capacitación Práctica (OJT).', null=True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='fecha_teorico',
            field=models.DateField(blank=True, help_text='Fecha en que el candidato ingresó a Capacitación Teórica.', null=True),
        ),
    ]
