# Generated by Django 5.2.7 on 2025-10-22 18:44

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0004_proceso_fecha_practico_proceso_fecha_teorico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroasistencia',
            options={'ordering': ['-momento_registro'], 'verbose_name_plural': 'Registros de Asistencia'},
        ),
        migrations.AlterUniqueTogether(
            name='registroasistencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='candidato',
            field=models.ForeignKey(blank=True, help_text='Candidato asociado (duplicado para optimización de consultas).', null=True, on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='fase_actual',
            field=models.CharField(choices=[('CONVOCADO', 'Convocado'), ('TEORIA', 'Capacitación Teórica'), ('PRACTICA', 'Capacitación Práctica (OJT)')], default=datetime.datetime(2025, 10, 22, 18, 44, 48, 697655, tzinfo=datetime.timezone.utc), max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='momento_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('REGISTRO', 'Registro Único')], default='REGISTRO', max_length=8),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('A', 'Asistió (Puntual)'), ('T', 'Tardanza'), ('F', 'Faltó'), ('J', 'Justificado')], default='A', max_length=1),
        ),
        migrations.RemoveField(
            model_name='registroasistencia',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='registroasistencia',
            name='tipo',
        ),
    ]
