# Generated by Django 5.2.7 on 2025-10-22 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0005_alter_registroasistencia_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='estado_asistencia',
            field=models.CharField(choices=[('A', 'Asistió'), ('F', 'Faltó'), ('T', 'Tardanza')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
