# Generated by Django 5.2.7 on 2025-10-25 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0006_registroasistencia_estado_asistencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_proceso', models.CharField(choices=[('INICIADO', 'Iniciado/Confirmado'), ('TEORIA', 'Capacitación Teórica'), ('PRACTICA', 'Capacitación Práctica'), ('CONTRATADO', 'Contratado'), ('NO_APTO', 'No Apto (No cumple pruebas/objetivos)'), ('ABANDONO', 'Abandono/Deserción')], default='INICIADO', help_text='Fase del proceso en el momento del registro del comentario.', max_length=150)),
                ('texto', models.TextField(help_text='Contenido de la observación o comentario.')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exactas del registro.')),
                ('proceso', models.ForeignKey(help_text='Proceso de convocatoria al que se le añade el comentario.', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='candidatos.proceso')),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que realizó la observación.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de Proceso',
                'verbose_name_plural': 'Comentarios de Procesos',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_proceso', models.CharField(choices=[('INICIADO', 'Iniciado/Confirmado'), ('TEORIA', 'Capacitación Teórica'), ('PRACTICA', 'Capacitación Práctica'), ('CONTRATADO', 'Contratado'), ('NO_APTO', 'No Apto (No cumple pruebas/objetivos)'), ('ABANDONO', 'Abandono/Deserción')], default='TEORIA', help_text='Fase del proceso en el momento del registro del test.', max_length=150)),
                ('tipo_test', models.CharField(choices=[('PSICOLOGICO', 'Test Psicológico'), ('CONOCIMIENTO', 'Test de Conocimiento'), ('VENTAS_PRACTICA', 'Simulación/Prueba de Ventas'), ('DOCUMENTO', 'Documento/Archivo Adicional'), ('OTRO', 'Otro')], help_text='Tipo de test o archivo subido.', max_length=50)),
                ('archivo_url', models.FileField(blank=True, help_text='Archivo subido (PDF, imagen, etc.).', null=True, upload_to='proceso_tests/%Y/%m/')),
                ('resultado_obtenido', models.CharField(blank=True, help_text="Resultado o calificación obtenida (ej. 'Apto', '9/10', 'No Apto').", max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exactas del registro.')),
                ('proceso', models.ForeignKey(help_text='Proceso de convocatoria al que pertenece el registro del test.', on_delete=django.db.models.deletion.CASCADE, related_name='tests_registrados', to='candidatos.proceso')),
                ('registrado_por', models.ForeignKey(blank=True, help_text='Usuario del sistema que registró el test/archivo.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Test/Archivo',
                'verbose_name_plural': 'Registros de Tests/Archivos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
