# Generated by Django 5.2.7 on 2025-10-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0007_comentarioproceso_registrotest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='estado_actual',
            field=models.CharField(choices=[('REGISTRADO', 'Registrado (Primer Contacto)'), ('CONVOCADO', 'Convocado (Segundo Contacto)'), ('CAPACITACION_TEORICA', 'En Capacitación Teórica'), ('CAPACITACION_PRACTICA', 'En Capacitación Práctica'), ('NO_APTO', 'No Apto (Descarte por rendimiento)'), ('DESISTE', 'Desiste / No Confirmó / Abandona'), ('CONTRATADO', 'Contratado')], default='REGISTRADO', max_length=250),
        ),
    ]
