# Generated by Django 5.2.7 on 2025-10-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0008_alter_candidato_estado_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='edad',
            field=models.IntegerField(blank=True, help_text='Edad del candidato.', null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='motivo_descarte',
            field=models.CharField(blank=True, choices=[('NO_CONFIRMA', 'No Confirma Asistencia'), ('NO_SE_PRESENTE', 'No Se Presentó'), ('SALARIO_NO_CONVENIENTE', 'Salario No Conveniente'), ('PROBLEMAS_PERSONALES', 'Problemas Personales'), ('OTRO', 'Otro Motivo')], help_text='Motivo por el cual el candidato desistió o fue descartado.', max_length=255, null=True),
        ),
    ]
