# Generated by Django 5.2.7 on 2025-10-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0009_candidato_edad_candidato_motivo_descarte'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='kanban_activo',
            field=models.BooleanField(default=True),
        ),
    ]
