# Generated by Django 5.2.7 on 2025-11-05 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0011_candidato_usuario_ultima_modificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CERTIFICADO_LABORAL', 'Certificado de Experiencia Laboral'), ('CUL', 'Certificado Único Laboral (CUL)'), ('ANTECEDENTES', 'Certificado de Antecedentes'), ('CURRICULUM', 'Curriculum Vitae (CV)'), ('OTRO', 'Otro Documento')], max_length=50, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='candidatos/documentos/', verbose_name='Archivo Adjunto')),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_laborales', to='candidatos.candidato', verbose_name='Candidato Asociado')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidatos.proceso', verbose_name='Proceso Relacionado')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Subió')),
            ],
            options={
                'verbose_name': 'Documento del Candidato',
                'verbose_name_plural': 'Documentos del Candidato',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
