# Generated by Django 5.2.7 on 2025-11-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0012_documentocandidato'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Documento (Ej: DNI, Cédula)')),
                ('codigo_pais', models.CharField(max_length=5, unique=True, verbose_name='Código de País (Ej: PER, COL)')),
                ('longitud_requerida', models.IntegerField(blank=True, null=True, verbose_name='Longitud Fija (Ej: 8 para DNI)')),
                ('solo_numeros', models.BooleanField(default=True, verbose_name='Requiere solo caracteres numéricos')),
            ],
            options={
                'verbose_name': 'Tipo de Documento de Identidad',
                'verbose_name_plural': 'Tipos de Documento de Identidad',
            },
        ),
    ]
