# Generated by Django 5.2.7 on 2025-11-06 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0013_tipodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='tipo_documento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='candidatos.tipodocumento', verbose_name='Tipo de Identificación'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='DNI',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Número de Documento'),
        ),
    ]
