# Generated by Django 5.2.7 on 2025-11-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0014_candidato_tipo_documento_alter_candidato_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='kanban_activo',
            field=models.BooleanField(default=True, help_text='Controla si el candidato es visible en el tablero Kanban/Dashboard.'),
        ),
    ]
