# Generated by Django 5.2.7 on 2025-11-13 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0015_candidato_kanban_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajePlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Nombre que identifica la plantilla, ej: 'CONVOCATORIA_LUNES_9AM'", max_length=100, unique=True, verbose_name='Título Único de la Plantilla')),
                ('contenido_texto', models.TextField(help_text='Texto con las variables de personalización (ej: {nombres_completos}).', verbose_name='Contenido del Mensaje')),
                ('variables_usadas', models.CharField(blank=True, help_text='Variables de Candidato usadas en el texto (separadas por coma), ej: DNI, telefono_whatsapp, sede_registro.', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Mensaje',
                'verbose_name_plural': 'Plantillas de Mensajes',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='TareaEnvioMasivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceso_tipo', models.CharField(choices=[('GLOBAL', 'Envío Global/Múltiples Estados'), ('REGISTRADO', 'Registrado (Primer Contacto)'), ('CONVOCADO', 'Convocado (Segundo Contacto)'), ('CAPACITACION_TEORICA', 'En Capacitación Teórica')], default='GLOBAL', help_text="Estado/Filtro usado para seleccionar a los candidatos (Corresponde a tu campo 'Proceso' en el modal).", max_length=50, verbose_name='Filtro de Proceso Usado')),
                ('fecha_origen', models.DateField(help_text="Fecha de registro o modificación que se usó como filtro (Corresponde a tu campo 'Fecha Origen' en el modal).", verbose_name='Fecha de Origen de los Datos')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio del Envío')),
                ('total_contactos', models.PositiveIntegerField(default=0, help_text='Número total de contactos que deberían recibir el mensaje.')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente (En cola de Celery)'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido (Error en el worker)')], default='PENDIENTE', max_length=15)),
                ('task_id', models.CharField(blank=True, help_text='ID de la tarea en Celery para seguimiento asíncrono.', max_length=255, null=True, unique=True)),
                ('total_entregados', models.PositiveIntegerField(default=0)),
                ('total_fallidos', models.PositiveIntegerField(default=0)),
                ('mensaje_plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidatos.mensajeplantilla', verbose_name='Plantilla Enviada')),
                ('usuario_que_envia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema')),
            ],
            options={
                'verbose_name': 'Tarea de Envío Masivo',
                'verbose_name_plural': 'Tareas de Envío Masivo',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(help_text='Teléfono final usado (campo telefono_whatsapp del Candidato).', max_length=20)),
                ('contenido_final', models.TextField(help_text='Contenido del mensaje después de la personalización de variables.')),
                ('estado_meta', models.CharField(choices=[('ENVIADO', 'Enviado (a la cola de Meta)'), ('ENTREGADO', 'Entregado (al dispositivo del usuario)'), ('LEIDO', 'Leído (por el usuario)'), ('FALLIDO', 'Fallido (error en el envío/número inválido)')], default='ENVIADO', max_length=15, verbose_name='Estado de WhatsApp')),
                ('id_mensaje_meta', models.CharField(blank=True, help_text='ID único devuelto por la API de Meta/WhatsApp (Webhook ID).', max_length=255, null=True, unique=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidatos.candidato', verbose_name='Candidato/Contacto')),
                ('tarea_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_envio', to='candidatos.tareaenviomasivo', verbose_name='Campaña/Tarea Asociada')),
            ],
            options={
                'verbose_name': 'Detalle de Envío Individual',
                'verbose_name_plural': 'Detalles de Envíos Individuales',
                'ordering': ['-fecha_envio'],
                'unique_together': {('tarea_envio', 'contacto')},
            },
        ),
    ]
