# Generated by Django 5.2.7 on 2025-11-13 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0016_mensajeplantilla_tareaenviomasivo_detalleenvio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleenvio',
            name='contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidatos.candidato', verbose_name='Candidato/Contacto'),
        ),
    ]
