# Generated by Django 5.2.7 on 2025-11-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0017_alter_detalleenvio_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleenvio',
            name='estado_meta',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('LEIDO', 'Leído'), ('FALLIDO', 'Fallido')], default='ENVIADO', max_length=15, verbose_name='Estado de WhatsApp'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], default='REGISTRO', max_length=8),
        ),
    ]
