# Generated by Django 5.2.7 on 2025-11-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0018_alter_detalleenvio_estado_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], default='ENTRADA', max_length=8),
        ),
    ]
