# Generated by Django 5.2.7 on 2025-11-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0019_alter_registroasistencia_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroasistencia',
            name='estado_asistencia',
        ),
    ]
