# Generated by Django 5.2.7 on 2025-11-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0020_remove_registroasistencia_estado_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='estado_asistencia',
            field=models.CharField(choices=[('A', 'Asistió'), ('F', 'Faltó'), ('T', 'Tardanza')], default='A', max_length=1),
        ),
    ]
