# Generated by Django 5.2.7 on 2025-11-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0021_registroasistencia_estado_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='estado_actual',
            field=models.CharField(choices=[('REGISTRADO', 'Registrado (Primer Contacto)'), ('CONVOCADO', 'Convocado (Segundo Contacto)'), ('CONFIRMADO', 'Confirmado'), ('CAPACITACION_TEORICA', 'En Capacitación Teórica'), ('CAPACITACION_PRACTICA', 'En Capacitación Práctica'), ('NO_APTO', 'No Apto (Descarte por rendimiento)'), ('DESISTE', 'Desiste / No Confirmó / Abandona'), ('CONTRATADO', 'Contratado')], default='REGISTRADO', max_length=250),
        ),
        migrations.AlterField(
            model_name='comentarioproceso',
            name='fase_proceso',
            field=models.CharField(choices=[('CONVOCADO', 'Convocado'), ('INICIADO', 'Confirmado'), ('TEORIA', 'Capacitación Teórica'), ('PRACTICA', 'Capacitación Práctica'), ('CONTRATADO', 'Contratado'), ('NO_APTO', 'No Apto (No cumple pruebas/objetivos)'), ('ABANDONO', 'Abandono/Deserción')], default='INICIADO', help_text='Fase del proceso en el momento del registro del comentario.', max_length=150),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('CONVOCADO', 'Convocado'), ('INICIADO', 'Confirmado'), ('TEORIA', 'Capacitación Teórica'), ('PRACTICA', 'Capacitación Práctica'), ('CONTRATADO', 'Contratado'), ('NO_APTO', 'No Apto (No cumple pruebas/objetivos)'), ('ABANDONO', 'Abandono/Deserción')], default='INICIADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='fase_actual',
            field=models.CharField(choices=[('CONVOCADO', 'Convocado'), ('INICIADO', 'Confirmado'), ('TEORIA', 'Capacitación Teórica'), ('PRACTICA', 'Capacitación Práctica (OJT)')], max_length=15),
        ),
        migrations.AlterField(
            model_name='registrotest',
            name='fase_proceso',
            field=models.CharField(choices=[('CONVOCADO', 'Convocado'), ('INICIADO', 'Confirmado'), ('TEORIA', 'Capacitación Teórica'), ('PRACTICA', 'Capacitación Práctica'), ('CONTRATADO', 'Contratado'), ('NO_APTO', 'No Apto (No cumple pruebas/objetivos)'), ('ABANDONO', 'Abandono/Deserción')], default='TEORIA', help_text='Fase del proceso en el momento del registro del test.', max_length=150),
        ),
        migrations.AlterField(
            model_name='tareaenviomasivo',
            name='proceso_tipo',
            field=models.CharField(choices=[('GLOBAL', 'Envío Global/Múltiples Estados'), ('REGISTRADO', 'Registrado (Primer Contacto)'), ('CONVOCADO', 'Convocado (Segundo Contacto)'), ('CONFIRMADO', 'Confirmado'), ('CAPACITACION_TEORICA', 'En Capacitación Teórica')], default='GLOBAL', help_text="Estado/Filtro usado para seleccionar a los candidatos (Corresponde a tu campo 'Proceso' en el modal).", max_length=50, verbose_name='Filtro de Proceso Usado'),
        ),
    ]
