# Generated by Django 5.2.7 on 2025-11-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0022_alter_candidato_estado_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioproceso',
            name='fase_proceso',
            field=models.CharField(choices=[('CONVOCADO', 'Convocado'), ('CONFIRMADO', 'Confirmado'), ('TEORIA', 'Capacitación Teórica'), ('PRACTICA', 'Capacitación Práctica'), ('CONTRATADO', 'Contratado'), ('NO_APTO', 'No Apto (No cumple pruebas/objetivos)'), ('ABANDONO', 'Abandono/Deserción')], default='INICIADO', help_text='Fase del proceso en el momento del registro del comentario.', max_length=150),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('CONVOCADO', 'Convocado'), ('CONFIRMADO', 'Confirmado'), ('TEORIA', 'Capacitación Teórica'), ('PRACTICA', 'Capacitación Práctica'), ('CONTRATADO', 'Contratado'), ('NO_APTO', 'No Apto (No cumple pruebas/objetivos)'), ('ABANDONO', 'Abandono/Deserción')], default='INICIADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='registrotest',
            name='fase_proceso',
            field=models.CharField(choices=[('CONVOCADO', 'Convocado'), ('CONFIRMADO', 'Confirmado'), ('TEORIA', 'Capacitación Teórica'), ('PRACTICA', 'Capacitación Práctica'), ('CONTRATADO', 'Contratado'), ('NO_APTO', 'No Apto (No cumple pruebas/objetivos)'), ('ABANDONO', 'Abandono/Deserción')], default='TEORIA', help_text='Fase del proceso en el momento del registro del test.', max_length=150),
        ),
    ]
