# Generated by Django 5.2.7 on 2025-11-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0023_alter_comentarioproceso_fase_proceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='fecha_confirmado',
            field=models.CharField(blank=True, help_text='Fecha en el que el cadidato pasó a Confirmado', null=True),
        ),
        migrations.AlterField(
            model_name='comentarioproceso',
            name='fase_proceso',
            field=models.CharField(choices=[('CONVOCADO', 'Convocado'), ('CONFIRMADO', 'Confirmado'), ('TEORIA', 'Capacitación Teórica'), ('PRACTICA', 'Capacitación Práctica'), ('CONTRATADO', 'Contratado'), ('NO_APTO', 'No Apto (No cumple pruebas/objetivos)'), ('ABANDONO', 'Abandono/Deserción')], default='CONVOCADO', help_text='Fase del proceso en el momento del registro del comentario.', max_length=150),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='estado',
            field=models.CharField(choices=[('CONVOCADO', 'Convocado'), ('CONFIRMADO', 'Confirmado'), ('TEORIA', 'Capacitación Teórica'), ('PRACTICA', 'Capacitación Práctica'), ('CONTRATADO', 'Contratado'), ('NO_APTO', 'No Apto (No cumple pruebas/objetivos)'), ('ABANDONO', 'Abandono/Deserción')], default='CONVOCADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='fase_actual',
            field=models.CharField(choices=[('CONVOCADO', 'Convocado'), ('CONFIRMADO', 'Confirmado'), ('TEORIA', 'Capacitación Teórica'), ('PRACTICA', 'Capacitación Práctica (OJT)')], max_length=15),
        ),
        migrations.AlterField(
            model_name='tareaenviomasivo',
            name='proceso_tipo',
            field=models.CharField(choices=[('GLOBAL', 'Envío Global/Múltiples Estados'), ('REGISTRADO', 'Registrado (Primer Contacto)'), ('CONVOCADO', 'Convocado (Segundo Contacto)'), ('CONFIRMADO', 'Confirmado'), ('CAPACITACION_TEORICA', 'En Capacitación Teórica'), ('CONTRATADO', 'Contratado')], default='GLOBAL', help_text="Estado/Filtro usado para seleccionar a los candidatos (Corresponde a tu campo 'Proceso' en el modal).", max_length=50, verbose_name='Filtro de Proceso Usado'),
        ),
    ]
