# Generated by Django 5.2.7 on 2025-11-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0024_proceso_fecha_confirmado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='estado_actual',
            field=models.CharField(choices=[('REGISTRADO', 'Registrado'), ('CONVOCADO', 'Convocado'), ('CONFIRMADO', 'Confirmado'), ('CAPACITACION_TEORICA', 'En Capacitación Teórica'), ('CAPACITACION_PRACTICA', 'En Capacitación Práctica'), ('NO_APTO', 'No Apto (Descarte por rendimiento)'), ('DESISTE', 'Desiste / No Confirmó / Abandona'), ('CONTRATADO', 'Contratado')], default='REGISTRADO', max_length=250),
        ),
    ]
