# Generated by Django 5.2.7 on 2025-11-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0025_alter_candidato_estado_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='fecha_confirmado',
            field=models.DateField(blank=True, help_text='Fecha en el que el cadidato pasó a Confirmado', null=True),
        ),
    ]
