# Generated by Django 5.2.7 on 2025-11-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0026_alter_proceso_fecha_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='color_primario',
            field=models.CharField(default='blue-600', help_text='Color Tailwind CSS principal (ej: red-600, blue-900).', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='color_secundario',
            field=models.CharField(default='gray-100', help_text='Color Tailwind CSS secundario (ej: gray-100, yellow-300).', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo principal de la empresa.', null=True, upload_to='logos_empresa/'),
        ),
    ]
