# Generated by Django 5.2.7 on 2025-12-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0027_empresa_color_primario_empresa_color_secundario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='factor_actitud_aplica',
        ),
        migrations.AddField(
            model_name='proceso',
            name='factor_aptitud_aplica',
            field=models.BooleanField(default=False, help_text="Indica si se queda por 'Aptitud' a pesar de fallar otras pruebas (Opción escasa)."),
        ),
    ]
