# Generated by Django 5.2.7 on 2025-12-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0028_remove_proceso_factor_actitud_aplica_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarioproceso',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='datoscualificacion',
            options={'verbose_name_plural': 'Formulario'},
        ),
        migrations.AlterModelOptions(
            name='detalleenvio',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Detalle de Envío', 'verbose_name_plural': 'Detalles de Envíos'},
        ),
        migrations.AlterModelOptions(
            name='documentocandidato',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Documento Cv', 'verbose_name_plural': 'Documentos Cv'},
        ),
        migrations.AlterModelOptions(
            name='proceso',
            options={'verbose_name_plural': 'Procesos'},
        ),
        migrations.AlterModelOptions(
            name='registroasistencia',
            options={'verbose_name_plural': 'Asistencia'},
        ),
        migrations.AlterModelOptions(
            name='registrotest',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Test / Archivo', 'verbose_name_plural': 'Tests / Archivos'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'verbose_name_plural': 'Sedes'},
        ),
        migrations.AlterModelOptions(
            name='supervisor',
            options={'verbose_name_plural': 'Supervisores'},
        ),
        migrations.AlterModelOptions(
            name='tareaenviomasivo',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Lista de Envío', 'verbose_name_plural': 'Lista de Envíos'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'verbose_name': 'Tipo Documento', 'verbose_name_plural': 'Tipo Documento'},
        ),
    ]
